apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinger
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pinger
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pinger
    spec:
      containers:
      - name: pinger
        image: eu.gcr.io/symbolic-datum-416912/pinger:latest
