# .github/workflows/ci-cd.yaml
name: CI/CD

on: push

job:
  push:
    name: Build Container and Push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY_JSON }}'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'
    - name: Configure Docker
      run: |
        gcloud auth configure-docker
    - name: Build ponger image
      run: docker build -t ponger:latest app/ponger
    - name: Build and push Docker image
      run: |
        docker push ponger:latest
   - name: Build pinger image
      run: docker build -t pinger:latest app/pinger
    - name: Build and push Docker image
      run: |
        docker push pinger:latest
